# Generated by Django 6.0.7 on 2026-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('league', models.CharField(blank=True, max_length=200)),
                ('stadium', models.CharField(blank=True, max_length=200)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='team_logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('colors', models.CharField(blank=True, help_text='e.g. Red & White', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
